# Generated by Django 2.2 on 2020-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200305_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='common_name',
            field=models.CharField(default='mango', max_length=100),
        ),
    ]
