# Generated by Django 2.2 on 2020-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200309_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='payment_address',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('crops', 'Crops'), ('vegetable', 'Vegetable'), ('meat', 'Meat')], max_length=100),
        ),
    ]
